// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEhcxGgewii83WsDPgB2J-_A5ZUurwgoM',
    appId: '1:15893194596:web:e8a7c46b4980e826d7fc71',
    messagingSenderId: '15893194596',
    projectId: 'm3hulb',
    authDomain: 'm3hulb.firebaseapp.com',
    storageBucket: 'm3hulb.appspot.com',
    measurementId: 'G-Z7X5Q62D7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwP3gDD8SGk_UXQmuh4EUk_Ue4J_1A6Uw',
    appId: '1:15893194596:android:76813877ea9a93dcd7fc71',
    messagingSenderId: '15893194596',
    projectId: 'm3hulb',
    storageBucket: 'm3hulb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNLuryHYb1w9gBPwahC09OdR3F53owBlw',
    appId: '1:15893194596:ios:a51ec32df7cf298ad7fc71',
    messagingSenderId: '15893194596',
    projectId: 'm3hulb',
    storageBucket: 'm3hulb.appspot.com',
    iosClientId: '15893194596-n4fqrh0sffti11j3rn1j14rcil10p995.apps.googleusercontent.com',
    iosBundleId: 'com.example.handloans',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNLuryHYb1w9gBPwahC09OdR3F53owBlw',
    appId: '1:15893194596:ios:a51ec32df7cf298ad7fc71',
    messagingSenderId: '15893194596',
    projectId: 'm3hulb',
    storageBucket: 'm3hulb.appspot.com',
    iosClientId: '15893194596-n4fqrh0sffti11j3rn1j14rcil10p995.apps.googleusercontent.com',
    iosBundleId: 'com.example.handloans',
  );
}
